### ISSUE TITLE
Permission to Use In Modrinth Modpack

### ISSUE THREAD

**Issue by RiftSpatial** [jtorleon-studios-team/libraryferret#21]
I'm not sure where to ask this, but I am adding Modrinth support for my CurseForge modpack, however, Library Ferret, due to licensing restrictions, is not allowed in a Modrinth modpack without given permission. I apologize if this isn't the place to ask, but I couldn't find anywhere else. If it is alright, may I have permission to feature your mod in my modpack?

**Comment by RiftSpatial** [comment]
May I add, it is only because of the items it adds that I need it, the server has it because of it's a dependency, and you cannot join it because of those items.

**Comment by Lilith-Daemon** [comment]
Would second this that I would love to add it to a modrinth pack for me & my friends

**Comment by tmslpm** [comment]
Hello, we'll be posting on modrinth soon (https://modrinth.com/user/jtorleon_studios). 
Thank you for your interest in the jtorleon studios mod.
