### ISSUE TITLE
1.16.5 forge 2.0.0 crashing game on forge loader

### ISSUE THREAD

**Issue by Jetpack-Cat** [jtorleon-studios-team/libraryferret#3]
https://gist.github.com/Jetpack-Cat/915f267ffa7c40b30bc5aa3e0776a947

**Comment by jtorleonstudios** [comment]
line 7 

`java.lang.NullPointerException: KubeJS has not been initialized, this won't happen unless some OTHER mod failed to load first! Check your latest.log! `
